In [1]:
import numpy as np

### Creating Arrays

__np.array__

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
arr2d = np.array([[1,2,3],[4,6,5],[8,7,9]])

In [5]:
arr2d

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 9]])

In [6]:
arr3d = np.array([[[1,2,3],[4,6,5],[8,7,9]],[[11,12,13],[14,16,15],[18,17,19]]])

In [7]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  6,  5],
        [ 8,  7,  9]],

       [[11, 12, 13],
        [14, 16, 15],
        [18, 17, 19]]])

__np.zeros__

In [8]:
arrZero1d = np.zeros(5)

In [9]:
arrZero1d

array([0., 0., 0., 0., 0.])

In [10]:
arrZero2d = np.zeros((2,4))

In [11]:
arrZero2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arrZero3d = np.zeros((2,4,5))

In [13]:
arrZero3d

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

__np.ones__

In [14]:
arrOnes1d = np.ones(5)

In [15]:
arrOnes1d

array([1., 1., 1., 1., 1.])

In [16]:
arrOnes2d = np.ones((3,5))

In [17]:
arrOnes2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
arrOnes3d = np.ones((2,3,4))

In [19]:
arrOnes3d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

__np.eye(it only create 2d array for 1d flatten it and for 3d stack two diff)__

In [20]:
arrEye =np.eye(3)

In [21]:
arrEye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arrEye2 = np.eye(3)

In [23]:
arrEye2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
three_d_array = np.stack((arrEye, arrEye2))

In [25]:
three_d_array

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

__np.full((size),value)__

In [26]:
arrFull = np.full((2,3,4),8)

In [27]:
arrFull

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

__np.random.rand() Create array filled with random values between [0 to 1)__

In [28]:
arrRan = np.random.rand(2,2,3)

In [29]:
arrRan

array([[[0.73216924, 0.31854212, 0.04101147],
        [0.44447446, 0.02671491, 0.92266105]],

       [[0.15038415, 0.54814057, 0.76770405],
        [0.57978379, 0.4040044 , 0.52957708]]])

__np.arange create an array with a range numpy.arange(start,stop, step, dtype=None)__ cant create 3d array with that you can reshape it

In [30]:
arrArange = np.arange(0,8,)

In [31]:
arrArange

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
arrRes = arrArange.reshape(2,2,2)

In [33]:
arrRes

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

__np.linspace(): create evenly spaced numbers__

In [34]:
'''python
Copy code
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
Parameters:
start: The starting value of the sequence (inclusive).
stop: The end value of the sequence (inclusive by default).
num (optional): The number of samples to generate. The default is 50.
endpoint (optional): A boolean that determines whether to include the stop value in the output. The default is True.
'''

'python\nCopy code\nnumpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)\nParameters:\nstart: The starting value of the sequence (inclusive).\nstop: The end value of the sequence (inclusive by default).\nnum (optional): The number of samples to generate. The default is 50.\nendpoint (optional): A boolean that determines whether to include the stop value in the output. The default is True.\n'

In [35]:
arrLinspace = np.linspace(0,50,11)

In [36]:
arrLinspace

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

### Array Attributes

__Return Shape__

In [37]:
arr.shape

(3,)

In [38]:
arr2d.shape

(3, 3)

In [39]:
arr3d.shape

(2, 3, 3)

__arr.size__

In [40]:
arr.size

3

In [41]:
arr2d.size

9

In [42]:
arr3d.size

18

__arr.ndim__

In [43]:
arr.ndim

1

In [44]:
arr2d.ndim

2

In [45]:
arr3d.ndim

3

__arr.dtype__

In [46]:
arr.dtype

dtype('int32')

In [47]:
arr2d.dtype

dtype('int32')

__arr.itemsize(Size of element in bytes)__

In [48]:
arr.itemsize

4

### Reshaping and transposing arrays

__arr.reshape__

In [49]:
arrArange = np.arange(0,16)

In [50]:
arrArange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
arrArange.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [52]:
arr2d

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 9]])

In [53]:
arr2d.T

array([[1, 4, 8],
       [2, 6, 7],
       [3, 5, 9]])

In [54]:
arrArange.T #Doesnt transpose 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Mathematical Operations

In [55]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [56]:
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

__np.add__

In [57]:
print(f"{arr} + \n {arr2} = \n {np.add(arr,arr2)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] + 
 [[9 8 7]
 [6 5 4]
 [3 2 1]] = 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


__np.subtract()__

In [58]:
print(f"{arr} + \n {arr2} = \n {np.subtract(arr,arr2)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] + 
 [[9 8 7]
 [6 5 4]
 [3 2 1]] = 
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


__np.multiply__

In [59]:
print(f"{arr} + \n {arr2} = \n {np.multiply(arr,arr2)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] + 
 [[9 8 7]
 [6 5 4]
 [3 2 1]] = 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


__np.dot__

In [60]:
print(f"{arr} + \n {arr2} = \n {np.dot(arr,arr2)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] + 
 [[9 8 7]
 [6 5 4]
 [3 2 1]] = 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [61]:
print(f"{arr} + \n {arr2} = \n {arr@arr2}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] + 
 [[9 8 7]
 [6 5 4]
 [3 2 1]] = 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


__np.sum__

In [62]:
np.sum(arr)

45

In [63]:
np.mean(arr)

5.0

In [64]:
np.min(arr)

1

In [65]:
np.max(arr)

9

In [66]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [67]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

### Sorting and Searching

In [68]:
arr = np.array([[3,43,1],[8,3,55],[422,4,2]])

In [69]:
arr

array([[  3,  43,   1],
       [  8,   3,  55],
       [422,   4,   2]])

In [70]:
np.sort(arr) #Sort each row

array([[  1,   3,  43],
       [  3,   8,  55],
       [  2,   4, 422]])

In [71]:
np.argsort(arr) #return argument in which sorting will be good or at what place which index

array([[2, 0, 1],
       [1, 0, 2],
       [2, 1, 0]], dtype=int64)

In [72]:
np.argmax(arr) # it flatten the matrix first and cal index then

6

In [73]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  6,  5],
        [ 8,  7,  9]],

       [[11, 12, 13],
        [14, 16, 15],
        [18, 17, 19]]])

In [74]:
np.argmax(arr3d)

17

In [75]:
np.argmin(arr)

2

In [76]:
arr2d

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 9]])

In [77]:
np.where(arr2d>5) # column index and second array of row index

(array([1, 2, 2, 2], dtype=int64), array([1, 0, 1, 2], dtype=int64))

### Random Module

In [78]:
np.random.rand(2,2) #same as np.random.random((2,2))

array([[0.35443482, 0.30752919],
       [0.55059067, 0.30511541]])

In [79]:
np.random.randint(5,9,size=(2,3)) # np.random.randint(start,end,size=(c*r))

array([[5, 8, 7],
       [7, 5, 8]])

In [80]:
arr = np.arange(0,10)

In [81]:
np.random.choice(arr) #Choose ranom element form array

8

In [82]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [83]:
np.random.shuffle(arr2)

In [84]:

arr2

array([[6, 5, 4],
       [3, 2, 1],
       [9, 8, 7]])

### Statistical Functions

In [85]:
arr = np.arange(0,10)

In [86]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.mean(arr)

4.5

In [88]:
arr2d

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 9]])

In [89]:
np.mean(arr2d)

5.0

In [90]:
np.median(arr2d)

5.0

In [91]:
np.std(arr2d)

2.581988897471611

In [92]:
np.var(arr2d)

6.666666666666667

### Broadcasting and Vectorization

In [93]:
arr2d

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 9]])

In [94]:
arr2d + 3

array([[ 4,  5,  6],
       [ 7,  9,  8],
       [11, 10, 12]])

In [95]:
arr2d * 2

array([[ 2,  4,  6],
       [ 8, 12, 10],
       [16, 14, 18]])

In [96]:
arr2d - 3

array([[-2, -1,  0],
       [ 1,  3,  2],
       [ 5,  4,  6]])

In [97]:
arr2d % 2

array([[1, 0, 1],
       [0, 0, 1],
       [0, 1, 1]], dtype=int32)

In [98]:
arr33 = arr2d.copy()

In [99]:
arr33

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 9]])

In [100]:
arr2d

array([[1, 2, 3],
       [4, 6, 5],
       [8, 7, 9]])

In [101]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  6,  5],
        [ 8,  7,  9]],

       [[11, 12, 13],
        [14, 16, 15],
        [18, 17, 19]]])

### Indexing and Slicing

In [104]:
arr3d[1,2,1]

17

In [109]:
arr3d[:,:,1]

array([[ 2,  6,  7],
       [12, 16, 17]])

In [110]:
arr3d[:,0:2,0:2]

array([[[ 1,  2],
        [ 4,  6]],

       [[11, 12],
        [14, 16]]])

### Linear Algebra